name = "bmw-dashboard"
main = "src/x3-site.js"
compatibility_date = "2024-01-01"
keep_vars = true

[[d1_databases]]
binding = "DB"
database_name = "bmw-vehicle-data"
database_id = ""

[[routes]]
pattern = "bmw.samuelecorona.it"
custom_domain = true

[[routes]]
pattern = "bmw-x3.samuelecorona.it"
custom_domain = true
