import legacy from "./worker.js";

const html = `<!doctype html>
<html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>BMW X3 · Drive Intelligence</title>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"><\/script>
<style>
:root{--bg:#080b10;--panel:#11161e;--panel2:#151c25;--line:#252e39;--text:#f4f7fb;--muted:#8f9baa;--blue:#4d8dff;--green:#62d69a;--amber:#f2bf63}
*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 75% -10%,#152238 0,transparent 35%),var(--bg);color:var(--text);font-family:-apple-system,BlinkMacSystemFont,"SF Pro Display","Segoe UI",sans-serif}
a{color:inherit;text-decoration:none}.shell{max-width:1280px;margin:auto;padding:0 24px 50px}.top{height:72px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}
.brand{display:flex;align-items:center;gap:12px;font-weight:750}.mark{width:30px;height:30px;border:7px solid #eee;border-radius:50%;box-shadow:inset 0 0 0 3px #3984e6}.nav{display:flex;gap:8px}.nav a{padding:9px 13px;color:var(--muted);border-radius:10px;font-size:14px}.nav a.active,.nav a:hover{background:#18212d;color:white}
.hero{padding:44px 0 26px;display:grid;grid-template-columns:1.3fr .7fr;gap:24px;align-items:end}.eyebrow{font-size:12px;letter-spacing:.14em;text-transform:uppercase;color:var(--blue);font-weight:800}.hero h1{font-size:clamp(38px,6vw,72px);line-height:.95;margin:10px 0 14px;letter-spacing:-.055em}.hero p{color:var(--muted);font-size:17px;margin:0}.heroState{text-align:right}.heroState strong{font-size:34px}.heroState span{display:block;color:var(--muted);margin-top:6px}
.kpis{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:18px 0}.card{background:linear-gradient(145deg,var(--panel2),var(--panel));border:1px solid var(--line);border-radius:18px;padding:20px}.kpi small,.label{display:block;color:var(--muted);font-size:12px;margin-bottom:10px}.kpi strong{font-size:29px;letter-spacing:-.04em}.kpi em{font-style:normal;color:var(--muted);font-size:12px;display:block;margin-top:7px}
.grid{display:grid;grid-template-columns:1.25fr .75fr;gap:12px}.chart{height:250px}.sectionTitle{font-size:17px;margin:0 0 18px}.insights{display:grid;gap:10px}.insight{padding:13px 0;border-bottom:1px solid var(--line);font-size:14px;line-height:1.45}.insight:last-child{border:0}.insight b{display:block;margin-bottom:4px}.insight span{color:var(--muted)}
.lower{display:grid;grid-template-columns:1fr 1fr 1fr;gap:12px;margin-top:12px}.metricRow{display:flex;justify-content:space-between;gap:15px;padding:10px 0;border-bottom:1px solid var(--line);font-size:14px}.metricRow:last-child{border:0}.metricRow span{color:var(--muted)}.good{color:var(--green)}.warn{color:var(--amber)}
.bottomnav{display:none}.error{padding:18px;border:1px solid #6e3030;background:#291616;border-radius:14px;margin-top:20px}
@media(max-width:800px){.shell{padding:0 15px 90px}.top{height:60px}.nav{display:none}.hero{grid-template-columns:1fr;padding:28px 0 16px}.heroState{text-align:left}.kpis{grid-template-columns:1fr 1fr}.grid,.lower{grid-template-columns:1fr}.chart{height:210px}.bottomnav{position:fixed;z-index:10;display:flex;bottom:0;left:0;right:0;background:rgba(8,11,16,.92);backdrop-filter:blur(18px);border-top:1px solid var(--line);justify-content:space-around;padding:10px 5px calc(10px + env(safe-area-inset-bottom))}.bottomnav a{font-size:11px;color:var(--muted);text-align:center}.bottomnav b{display:block;color:white;font-size:17px;margin-bottom:2px}}
</style></head><body><div class="shell">
<header class="top"><div class="brand"><div class="mark"></div>BMW X3 M40d</div><nav class="nav"><a class="active" href="/">Overview</a><a href="/trips">Trips</a><a href="/x3-efficiency">Efficiency</a><a href="/fuel">Fuel & Cost</a><a href="/x3-vehicle">Vehicle</a><a href="/history">Data</a></nav></header>
<section class="hero"><div><div class="eyebrow">Drive intelligence</div><h1>La tua X3,<br>in numeri utili.</h1><p id="period">Caricamento storico BMW…</p></div><div class="heroState"><strong id="odo">—</strong><span id="fresh">Ultimo dato BMW</span></div></section>
<div id="err"></div>
<section class="kpis"><div class="card kpi"><small>30 giorni</small><strong id="km30">—</strong><em id="kmDay">distanza</em></div><div class="card kpi"><small>Efficienza reale</small><strong id="kml">—</strong><em id="kmlNote">da dati carburante</em></div><div class="card kpi"><small>Costo stimato</small><strong id="cost">—</strong><em id="costNote">ultimi 30 giorni</em></div><div class="card kpi"><small>Autonomia</small><strong id="range">—</strong><em id="fuel">carburante</em></div></section>
<section class="grid"><div class="card"><h2 class="sectionTitle">Quanto la stai usando</h2><div class="chart"><canvas id="kmChart"></canvas></div></div><div class="card"><h2 class="sectionTitle">Cosa conta adesso</h2><div id="insights" class="insights"></div></div></section>
<section class="lower"><div class="card"><h2 class="sectionTitle">Viaggi</h2><div id="tripBox"></div><a href="/trips" style="color:var(--blue);font-size:13px">Apri tutti i viaggi →</a></div><div class="card"><h2 class="sectionTitle">Pneumatici</h2><div id="tyres"></div><a href="/tyres" style="color:var(--blue);font-size:13px">Dettaglio pressioni →</a></div><div class="card"><h2 class="sectionTitle">Uso & costi</h2><div id="usage"></div><a href="/fuel" style="color:var(--blue);font-size:13px">Fuel & cost →</a></div></section>
</div>
<nav class="bottomnav"><a href="/"><b>⌂</b>Overview</a><a href="/trips"><b>↗</b>Trips</a><a href="/x3-efficiency"><b>◫</b>Efficiency</a><a href="/fuel"><b>€</b>Fuel</a><a href="/x3-vehicle"><b>◇</b>Vehicle</a></nav>
<script>
const $=id=>document.getElementById(id),fmt=(n,d=0)=>Number(n).toLocaleString('it-IT',{minimumFractionDigits:d,maximumFractionDigits:d});
function row(k,v,c=''){return '<div class="metricRow"><span>'+k+'</span><b class="'+c+'">'+v+'</b></div>'}
Promise.all([fetch('/api/data').then(r=>r.json()),fetch('/api/analytics?days=30').then(r=>r.json()),fetch('/api/fuel').then(r=>r.json()),fetch('/api/trips').then(r=>r.json())]).then(([d,a,f,t])=>{
 const mileage=d.core?.mileageKm||a.mileage?.lastOdometer; $('odo').textContent=mileage?fmt(mileage)+' km':'—';
 $('fresh').textContent=d.core?.mileageTimestamp?'Aggiornato '+new Date(d.core.mileageTimestamp).toLocaleString('it-IT',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'Ultimo dato disponibile';
 $('period').textContent=a.periodStart&&a.periodEnd?'Analisi '+new Date(a.periodStart+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'short'})+' – '+new Date(a.periodEnd+'T12:00:00').toLocaleDateString('it-IT',{day:'numeric',month:'short'}):'BMW CarData + storico';
 $('km30').textContent=a.mileage?.distanceKm!=null?fmt(a.mileage.distanceKm)+' km':'—'; $('kmDay').textContent=a.driving?.avgKmPerDay!=null?fmt(a.driving.avgKmPerDay,1)+' km/giorno':'distanza';
 const kml=a.fuel?.kmPerLitre; $('kml').textContent=kml?fmt(kml,1)+' km/L':'—'; $('kmlNote').textContent=a.fuel?.consumptionConfidence==='reliable'?'misura affidabile':a.fuel?.consumptionConfidence==='provisional'?'stima provvisoria':'raccolta dati in corso';
 const price=Number(f.dieselPrice||0),cost=kml&&price? a.mileage.distanceKm/kml*price:null; $('cost').textContent=cost?'~€ '+fmt(cost):'—'; $('costNote').textContent=price?'diesel € '+fmt(price,3)+'/L':'ultimi 30 giorni';
 $('range').textContent=d.core?.rangeKm!=null?fmt(d.core.rangeKm)+' km':'—'; $('fuel').textContent=d.core?.fuelPercent!=null?fmt(d.core.fuelPercent)+'% serbatoio':'carburante';
 const series=a.dailySeries||[]; new Chart($('kmChart'),{type:'bar',data:{labels:series.map(x=>x.date.slice(5)),datasets:[{data:series.map(x=>x.km),borderRadius:5,backgroundColor:'rgba(77,141,255,.72)'}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{display:false}},scales:{x:{grid:{display:false},ticks:{color:'#778392',maxTicksLimit:10}},y:{grid:{color:'#222b35'},ticks:{color:'#778392'}}}}});
 let ins=[]; if(a.driving?.longestDay?.km)ins.push(['Giornata più intensa',fmt(a.driving.longestDay.km)+' km · '+a.driving.longestDay.date]); if(a.mileage?.unallocatedGapKm>0)ins.push(['Copertura dati','Ci sono '+fmt(a.mileage.unallocatedGapKm)+' km non attribuiti a singoli giorni']); if(kml)ins.push(['Consumo 30 giorni',fmt(kml,1)+' km/L su '+fmt(a.fuel.fuelCoveredKm||0)+' km coperti']); if(d.tyres?.alerts?.any)ins.push(['Pneumatici','Una pressione è oltre la soglia rispetto al target']); else ins.push(['Pneumatici','Nessuna anomalia importante rilevata']); $('insights').innerHTML=ins.map(x=>'<div class="insight"><b>'+x[0]+'</b><span>'+x[1]+'</span></div>').join('');
 const trips=t.trips||t||[]; const arr=Array.isArray(trips)?trips:(trips.trips||[]); $('tripBox').innerHTML=row('Viaggi nel periodo',a.trips?.tripCount??arr.length)+row('Giorni guidati',a.driving?.observedDrivingDays??'—')+row('Media/giorno',a.driving?.avgKmPerDay!=null?fmt(a.driving.avgKmPerDay,1)+' km':'—');
 const ty=d.tyres||{}; $('tyres').innerHTML=row('Anteriore SX',ty.frontLeft!=null?fmt(ty.frontLeft,1)+' bar':'—',ty.alerts?.frontLeft?'warn':'good')+row('Anteriore DX',ty.frontRight!=null?fmt(ty.frontRight,1)+' bar':'—',ty.alerts?.frontRight?'warn':'good')+row('Posteriore SX',ty.rearLeft!=null?fmt(ty.rearLeft,1)+' bar':'—',ty.alerts?.rearLeft?'warn':'good')+row('Posteriore DX',ty.rearRight!=null?fmt(ty.rearRight,1)+' bar':'—',ty.alerts?.rearRight?'warn':'good');
 $('usage').innerHTML=row('Km / giorno',a.driving?.avgKmPerDay!=null?fmt(a.driving.avgKmPerDay,1):'—')+row('Prezzo diesel',price?'€ '+fmt(price,3)+'/L':'—')+row('Rifornimenti rilevati',f.refuels?.length??0);
}).catch(e=>{$('err').innerHTML='<div class="error">Impossibile caricare i dati: '+e.message+'</div>'});
</script></body></html>`;

function shellPage(title, eyebrow, body, script=""){
 return `<!doctype html><html lang="it"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} · BMW X3</title><style>:root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#080b10;color:#f4f7fb;font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.s{max-width:1100px;margin:auto;padding:24px}.top{display:flex;justify-content:space-between;align-items:center;padding:12px 0 30px}.top a{color:#8f9baa;text-decoration:none}.ey{color:#4d8dff;text-transform:uppercase;letter-spacing:.14em;font-size:12px;font-weight:800}h1{font-size:44px;letter-spacing:-.04em;margin:8px 0 28px}.g{display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px}.c{background:#121820;border:1px solid #252e39;border-radius:18px;padding:20px}.c small{color:#8f9baa}.c strong{display:block;font-size:28px;margin-top:8px}.wide{grid-column:1/-1}.row{display:flex;justify-content:space-between;padding:12px 0;border-bottom:1px solid #252e39}.row span{color:#8f9baa}@media(max-width:600px){h1{font-size:36px}.s{padding:16px}}</style></head><body><main class="s"><div class="top"><b>BMW X3 M40d</b><a href="/">← Overview</a></div><div class="ey">${eyebrow}</div><h1>${title}</h1>${body}</main><script>${script}<\/script></body></html>`;
}
const efficiency=shellPage("Efficiency","Driving intelligence",`<div class="g"><div class="c"><small>30 giorni</small><strong id="km">—</strong></div><div class="c"><small>Consumo</small><strong id="kml">—</strong></div><div class="c"><small>Km/giorno</small><strong id="avg">—</strong></div><div class="c"><small>Giorno più lungo</small><strong id="long">—</strong></div><div class="c wide" id="days"></div></div>`,`fetch('/api/analytics?days=30').then(r=>r.json()).then(a=>{km.textContent=(a.mileage?.distanceKm??'—')+' km';kml.textContent=a.fuel?.kmPerLitre?(a.fuel.kmPerLitre+' km/L'):'—';avg.textContent=(a.driving?.avgKmPerDay??'—')+' km';long.textContent=(a.driving?.longestDay?.km??'—')+' km';days.innerHTML='<b>Copertura</b><div class="row"><span>Giorni guidati</span><b>'+a.driving.observedDrivingDays+'</b></div><div class="row"><span>Km coperti dal calcolo carburante</span><b>'+a.fuel.fuelCoveredKm+' km</b></div><div class="row"><span>Affidabilità consumo</span><b>'+a.fuel.consumptionConfidence+'</b></div>'})`);
const vehicle=shellPage("Vehicle","Current status",`<div class="g"><div class="c"><small>Odometro</small><strong id="odo">—</strong></div><div class="c"><small>Autonomia</small><strong id="range">—</strong></div><div class="c"><small>Carburante</small><strong id="fuel">—</strong></div><div class="c"><small>Stato</small><strong id="state">—</strong></div><div class="c wide"><b>Pneumatici</b><div id="ty"></div></div></div>`,`fetch('/api/data').then(r=>r.json()).then(d=>{odo.textContent=(d.core?.mileageKm??'—')+' km';range.textContent=(d.core?.rangeKm??'—')+' km';fuel.textContent=(d.core?.fuelPercent??'—')+'%';state.textContent=d.quick?.vehicleState||'—';let t=d.tyres||{};ty.innerHTML=[['Ant. SX',t.frontLeft],['Ant. DX',t.frontRight],['Post. SX',t.rearLeft],['Post. DX',t.rearRight]].map(x=>'<div class="row"><span>'+x[0]+'</span><b>'+(x[1]??'—')+' bar</b></div>').join('')})`);

export default {
 async fetch(request,env,ctx){
   const u=new URL(request.url);
   if(request.method==="GET" && u.pathname==="/") {
     const probe=await legacy.fetch(new Request(u.origin+"/api/data",{headers:request.headers}),env,ctx);
     if(probe.status===401 || probe.status===303) return legacy.fetch(request,env,ctx);
     return new Response(html,{headers:{"content-type":"text/html;charset=utf-8","cache-control":"no-store"}});
   }
   if(request.method==="GET" && u.pathname==="/x3-efficiency") return new Response(efficiency,{headers:{"content-type":"text/html;charset=utf-8","cache-control":"no-store"}});
   if(request.method==="GET" && u.pathname==="/x3-vehicle") return new Response(vehicle,{headers:{"content-type":"text/html;charset=utf-8","cache-control":"no-store"}});
   return legacy.fetch(request,env,ctx);
 },
 scheduled(controller,env,ctx){return legacy.scheduled?.(controller,env,ctx)}
};